#!/usr/bin/env bash
# Render /var/www/html/config.php from Bitnami-compatible env vars.
# Idempotent: re-run on every container start to pick up env changes,
# but only overwrites if env-driven or file is missing.
set -euo pipefail

CONFIG_PHP="/var/www/html/config.php"
DATA_DIR="${MOODLE_DATA_DIR:-/bitnami/moodledata}"

# Map db type aliases (Bitnami accepts mariadb/mysql/postgresql forms)
case "${MOODLE_DATABASE_TYPE:-mariadb}" in
    mariadb|mysql|mysqli) DBTYPE="mariadb" ;;
    postgres|postgresql|pgsql) DBTYPE="pgsql" ;;
    sqlite|sqlite3) DBTYPE="sqlite3" ;;
    *) echo "[10-render-config] Unknown MOODLE_DATABASE_TYPE: ${MOODLE_DATABASE_TYPE}" >&2; exit 1 ;;
esac

# Default port per dbtype if not provided
DB_PORT="${MOODLE_DATABASE_PORT_NUMBER:-}"
if [ -z "${DB_PORT}" ]; then
    case "${DBTYPE}" in
        mariadb) DB_PORT="3306" ;;
        pgsql)   DB_PORT="5432" ;;
        sqlite3) DB_PORT="" ;;
    esac
fi

# wwwroot
if [ -n "${MOODLE_HOST:-}" ]; then
    PROTO="http"
    [ "${MOODLE_SSLPROXY:-no}" = "yes" ] && PROTO="https"
    WWWROOT="${PROTO}://${MOODLE_HOST}"
else
    WWWROOT="http://localhost:8080"
fi

REVERSEPROXY_BOOL="false"
[ "${MOODLE_REVERSEPROXY:-no}" = "yes" ] && REVERSEPROXY_BOOL="true"
SSLPROXY_BOOL="false"
[ "${MOODLE_SSLPROXY:-no}" = "yes" ] && SSLPROXY_BOOL="true"

mkdir -p "${DATA_DIR}"
# Maintain backward symlink expected by Bitnami users
if [ "${DATA_DIR}" != "/bitnami/moodledata" ] && [ ! -e "/bitnami/moodledata" ]; then
    mkdir -p /bitnami
    ln -sfn "${DATA_DIR}" /bitnami/moodledata 2>/dev/null || true
fi

# Generate config.php — overwritten each boot so env vars stay authoritative.
# User customizations belong in $CFG->config_php_settings overrides via files
# in /var/www/html/local/, not in config.php directly.
cat > "${CONFIG_PHP}" <<PHPEOF
<?php
// Auto-generated by moodle-alpine entrypoint. Do not edit by hand.
unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

\$CFG->dbtype    = '${DBTYPE}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${MOODLE_DATABASE_HOST:-}';
\$CFG->dbname    = '${MOODLE_DATABASE_NAME:-bitnami_moodle}';
\$CFG->dbuser    = '${MOODLE_DATABASE_USER:-bn_moodle}';
\$CFG->dbpass    = '${MOODLE_DATABASE_PASSWORD:-}';
\$CFG->prefix    = 'mdl_';
\$CFG->dboptions = array(
    'dbpersist' => 0,
    'dbsocket'  => false,
    'dbport'    => '${DB_PORT}',
    'dbhandlespersist' => false,
    'dbcollation' => 'utf8mb4_unicode_ci',
);

\$CFG->wwwroot   = '${WWWROOT}';
\$CFG->dataroot  = '${DATA_DIR}';
\$CFG->admin     = 'admin';
\$CFG->directorypermissions = 0775;

\$CFG->reverseproxy = ${REVERSEPROXY_BOOL};
\$CFG->sslproxy     = ${SSLPROXY_BOOL};

PHPEOF

# SMTP block (only if a host is configured)
if [ -n "${MOODLE_SMTP_HOST:-}" ]; then
    SMTP_HOSTS="${MOODLE_SMTP_HOST}"
    [ -n "${MOODLE_SMTP_PORT_NUMBER:-}" ] && SMTP_HOSTS="${SMTP_HOSTS}:${MOODLE_SMTP_PORT_NUMBER}"
    cat >> "${CONFIG_PHP}" <<PHPEOF
\$CFG->smtphosts        = '${SMTP_HOSTS}';
\$CFG->smtpuser         = '${MOODLE_SMTP_USER:-}';
\$CFG->smtppass         = '${MOODLE_SMTP_PASSWORD:-}';
\$CFG->smtpsecure       = '${MOODLE_SMTP_PROTOCOL:-}';
\$CFG->smtpauthtype     = 'LOGIN';
PHPEOF
fi

# SQLite needs a writable directory inside dataroot
if [ "${DBTYPE}" = "sqlite3" ]; then
    mkdir -p "${DATA_DIR}/sqlite"
    # Patch dbhost to point at the file path Moodle expects
    sed -i "s|\$CFG->dbname    = '.*';|\$CFG->dbname    = '${DATA_DIR}/sqlite/moodle.sqlite';|" "${CONFIG_PHP}"
fi

cat >> "${CONFIG_PHP}" <<'PHPEOF'

require_once(__DIR__ . '/lib/setup.php');
PHPEOF

echo "[10-render-config] config.php generated (dbtype=${DBTYPE}, host=${MOODLE_DATABASE_HOST:-}, wwwroot=${WWWROOT})"
