#!/usr/bin/env bash
# Render /var/www/html/config.php from Bitnami-compatible env vars.
# Idempotent: re-run on every container start to pick up env changes.
# Uses a PHP helper to safely escape all values (prevents code injection).
set -euo pipefail

CONFIG_PHP="/var/www/html/config.php"
DATA_DIR="${MOODLE_DATA_DIR:-/bitnami/moodledata}"

# Map db type aliases (Bitnami accepts mariadb/mysql/postgresql forms)
case "${MOODLE_DATABASE_TYPE:-mariadb}" in
    mariadb|mysql|mysqli) DBTYPE="mariadb" ;;
    postgres|postgresql|pgsql) DBTYPE="pgsql" ;;
    sqlite|sqlite3) DBTYPE="sqlite3" ;;
    *) echo "[10-render-config] Unknown MOODLE_DATABASE_TYPE: ${MOODLE_DATABASE_TYPE}" >&2; exit 1 ;;
esac

# Default port per dbtype if not provided
DB_PORT="${MOODLE_DATABASE_PORT_NUMBER:-}"
if [ -z "${DB_PORT}" ]; then
    case "${DBTYPE}" in
        mariadb) DB_PORT="3306" ;;
        pgsql)   DB_PORT="5432" ;;
        sqlite3) DB_PORT="" ;;
    esac
fi

# wwwroot — sanitise host: strip any accidental protocol and trailing slashes
if [ -n "${MOODLE_HOST:-}" ]; then
    CLEAN_HOST="$(echo "${MOODLE_HOST}" | sed -E 's#^https?://##;s#/+$##')"
    PROTO="http"
    [ "${MOODLE_SSLPROXY:-no}" = "yes" ] && PROTO="https"
    WWWROOT="${PROTO}://${CLEAN_HOST}"
else
    WWWROOT="http://localhost:8080"
fi

REVERSEPROXY_BOOL="false"
[ "${MOODLE_REVERSEPROXY:-no}" = "yes" ] && REVERSEPROXY_BOOL="true"
SSLPROXY_BOOL="false"
[ "${MOODLE_SSLPROXY:-no}" = "yes" ] && SSLPROXY_BOOL="true"

mkdir -p "${DATA_DIR}"
# Maintain backward symlink expected by Bitnami users
if [ "${DATA_DIR}" != "/bitnami/moodledata" ] && [ ! -e "/bitnami/moodledata" ]; then
    mkdir -p /bitnami
    ln -sfn "${DATA_DIR}" /bitnami/moodledata 2>/dev/null || true
fi

# --- Generate config.php via PHP to safely escape all values ---
# This prevents code injection from malicious env var values.
export DBTYPE DB_PORT WWWROOT REVERSEPROXY_BOOL SSLPROXY_BOOL DATA_DIR CONFIG_PHP

php -- <<'PHPGEN' > "${CONFIG_PHP}"
<?php
// Safely read env vars and escape for single-quoted PHP string literals.
// Only backslash and single-quote need escaping inside '...'; addslashes()
// would wrongly escape double quotes too, corrupting values that contain ".
function e(string $name, string $default = ''): string {
    $val = getenv($name) ?: $default;
    return str_replace(['\\', "'"], ['\\\\', "\\'"], $val);
}

$dbtype    = e('DBTYPE');
$dbhost    = e('MOODLE_DATABASE_HOST');
$dbname    = e('MOODLE_DATABASE_NAME', 'bitnami_moodle');
$dbuser    = e('MOODLE_DATABASE_USER', 'bn_moodle');
$dbpass    = e('MOODLE_DATABASE_PASSWORD');
$dbport    = e('DB_PORT');
$wwwroot   = e('WWWROOT');
$dataroot  = e('DATA_DIR', '/bitnami/moodledata');
$revproxy  = getenv('REVERSEPROXY_BOOL') === 'true' ? 'true' : 'false';
$sslproxy  = getenv('SSLPROXY_BOOL')   === 'true' ? 'true' : 'false';

echo "<?php\n";
echo "// Auto-generated by moodle-alpine entrypoint. Do not edit by hand.\n";
echo "unset(\$CFG);\n";
echo "global \$CFG;\n";
echo "\$CFG = new stdClass();\n\n";

echo "\$CFG->dbtype    = '{$dbtype}';\n";
echo "\$CFG->dblibrary = 'native';\n";
echo "\$CFG->dbhost    = '{$dbhost}';\n";
echo "\$CFG->dbname    = '{$dbname}';\n";
echo "\$CFG->dbuser    = '{$dbuser}';\n";
echo "\$CFG->dbpass    = '{$dbpass}';\n";
echo "\$CFG->prefix    = 'mdl_';\n";
echo "\$CFG->dboptions = array(\n";
echo "    'dbpersist' => 0,\n";
echo "    'dbsocket'  => false,\n";
echo "    'dbport'    => '{$dbport}',\n";
echo "    'dbhandlespersist' => false,\n";
echo "    'dbcollation' => 'utf8mb4_unicode_ci',\n";
echo ");\n\n";

echo "\$CFG->wwwroot   = '{$wwwroot}';\n";
echo "\$CFG->dataroot  = '{$dataroot}';\n";
echo "\$CFG->admin     = 'admin';\n";
echo "\$CFG->directorypermissions = 0775;\n\n";

echo "\$CFG->reverseproxy = {$revproxy};\n";
echo "\$CFG->sslproxy     = {$sslproxy};\n\n";

// SMTP block (only if a host is configured)
$smtp_hosts = e('MOODLE_SMTP_HOST');
$smtp_port  = e('MOODLE_SMTP_PORT_NUMBER');
$smtp_user  = e('MOODLE_SMTP_USER');
$smtp_pass  = e('MOODLE_SMTP_PASSWORD');
$smtp_proto = e('MOODLE_SMTP_PROTOCOL');

if ($smtp_hosts !== '') {
    if ($smtp_port !== '') {
        $smtp_hosts .= ':' . $smtp_port;
    }
    echo "\$CFG->smtphosts    = '{$smtp_hosts}';\n";
    echo "\$CFG->smtpuser     = '{$smtp_user}';\n";
    echo "\$CFG->smtppass     = '{$smtp_pass}';\n";
    echo "\$CFG->smtpsecure   = '{$smtp_proto}';\n";
    echo "\$CFG->smtpauthtype = 'LOGIN';\n\n";
}

echo "require_once(__DIR__ . '/lib/setup.php');\n";
PHPGEN

# SQLite needs a writable directory inside dataroot
if [ "${DBTYPE}" = "sqlite3" ]; then
    mkdir -p "${DATA_DIR}/sqlite"
    php -- <<'SQLITEFIX'
<?php
$file = getenv("CONFIG_PHP") ?: "/var/www/html/config.php";
$dir  = getenv("DATA_DIR")   ?: "/bitnami/moodledata";
$c    = file_get_contents($file);
$safe = addslashes($dir . "/sqlite/moodle.sqlite");
$c    = preg_replace(
    '/\$CFG->dbname\s+= \'[^\']*\';/',
    "\$CFG->dbname = '{$safe}';",
    $c
);
file_put_contents($file, $c);
SQLITEFIX
fi

echo "[10-render-config] done (db=${DBTYPE} wwwroot=${WWWROOT})"
